# -*- coding: utf-8 -*-
"""CIRQ circuit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqOyfIDaiF3eY5QyC73abMini4hGvM7t
"""


import cirq


qubit = cirq.GridQubit(0, 0)

circuit = cirq.Circuit(
    cirq.X(qubit)**0.5,  # Square root of NOT.
    cirq.measure(qubit, key='m')  # Measurement.
)
print("Circuit:")
print(circuit)


simulator = cirq.Simulator()
result = simulator.run(circuit, repetitions=20)
print("Results:")
print(result)
